### ISSUE TITLE
Hacktoberfest: Update Dependencies

### ISSUE THREAD

**Issue by ghost** [FusionAuth/fusionauth-quickstart-javascript-angular-web#4]
Verify that `complete-application` is up to date and working with the latest dependencies.

```shell
npm outdated
```

See also https://angular.io/cli/update

**Comment by beatrizsmerino** [comment]
Hello!!, 😊
I want to participate to fix this problem, can you assign me the task?

**Comment by ghost** [comment]
@beatrizsmerino assigned, to you. Happy hacking 👻

**Comment by beatrizsmerino** [comment]
Thank you very much I'll get to it!

**Comment by beatrizsmerino** [comment]
![image](https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/assets/14045148/c0a55fc2-f83a-44bf-af69-8b4935e0582c)
![image](https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/assets/14045148/fadb3bf9-8304-498c-a3fd-9b6d66a34d2c)

**Comment by ghost** [comment]
@beatrizsmerino feel free to open a PR on the repo when you are ready for me to test 😀

**Comment by beatrizsmerino** [comment]
> @beatrizsmerino feel free to open a PR on the repo when you are ready for me to test 😀

I got it, I was trying to update as many dependencies as possible.
You can check it in the PR https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/pull/6
