### ISSUE TITLE
404 Error on Request Being Made to Get --logo-url in Kickstart styles.css

### ISSUE THREAD

**Issue by BriDavidson** [FusionAuth/fusionauth-quickstart-javascript-angular-web#8]
**Description**
When attempting to pull in the `--logo-url` from the styles.css file, a `404` error is encountered this is notable within the console and network logging when viewing the Login page. It seems that the URL specified for `--logo-url` needs to be validated and updated or we may consider different handling if the logo is not required to show on this view.

**Steps to Reproduce**

1. Open the [styles.css](https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/blob/main/kickstart/css/styles.css) file.
2. Locate the `--logo-url` property in the `:root` section.
3. Attempt to access the URL specified for `--logo-url`.

**Expected Result**
The URL specified for `--logo-url` should be valid, and the logo image should be successfully loaded.

**Actual Result**
Encountering a `404` error when trying to access the URL specified for `--logo-url.`

**Supporting Test Artifacts**
https://jam.dev/c/94011928-c02b-4491-9926-43ba1eca0024

**Recommendation**

Validate the URL provided for `--logo-url` to ensure its correctness.
If the URL is incorrect or leads to a non-existent resource, update it with the correct and accessible URL for the logo image.
If the logo is not required to display in this view we should consider removing reference to the logo on this page

Please let me know if further information or clarification is needed.

**Comment by david-chalk** [comment]
@BriDavidson The CSS variable `--logo-url` does live in the Quickstart applications but isn't actually used.  It does point to a non-existent file but it's unused code. We can open issues to remove unused code in the Quickstart repos if we wanted to address that. 

The `404` you're seeing is from the FusionAuth instance trying to get that same resource. But it's unrelated to the SDKs or the Quickstart applications. A ticket will need to be made to fix that in the [FusionAuth issues](https://github.com/FusionAuth/fusionauth-issues) repo.

**Comment by JakeLo123** [comment]
This PR fixed it.
https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/pull/13
